### ISSUE TITLE
Error: BigInt value to a number

### ISSUE THREAD

**Issue by c0deCn** [paulmillr/noble-curves#43]
` TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at SWUFpSqrtRatio (weierstrass.js:1360:29)
    at mapToCurveSimpleSWU (weierstrass.js:1476:19)
    at eval (secp256k1.js:393:55)
    at ./node_modules/_@noble_curves@1.0.0@@noble/curves/secp256k1.js (chunk-vendors.js:15327:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at eval (index.js:3096:24)
    at ./node_modules/_@mysten_sui.js@0.32.2@@mysten/sui.js/dist/index.js (chunk-vendors.js:15243:1)
    at __webpack_require__ (app.js:854:30)
a`

I have tried many ways, but no solution

node -v: v16.16.0
"webpack": "^4.44.2",

**Comment by paulmillr** [comment]
you are using shitty bundler configuration. adjust it, this is not a noble problem.

**Comment by paulmillr** [comment]
probably `browserslist` is wrong, ensure it includes bigints

**Comment by c0deCn** [comment]
Any suggestions? Thank you

**Comment by c0deCn** [comment]
"browserslist": [
    "> 1%",
    "defaults and supports es6-module",
    "maintained node versions",
    "last 2 versions",
    "not dead"
  ],

**Comment by paulmillr** [comment]
```
"browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

try this

**Comment by c0deCn** [comment]
"browserslist": [
    "defaults and supports es6-module",
    "maintained node versions"
  ],


This worked, thank you!
